

-----------------------> LEER PARTE DE COMMANDS PARA CONTINUAR :v <-------------------------------


CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(70) NOT NULL,
  "password" varchar(50) NOT NULL,
  "age" smallint NOT NULL,
  "roles_id" smallint NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "description" varchar(70) NOT NULL,
  "level" varchar(30) NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(255) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "categories_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "users_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" int NOT NULL,
  "courses_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "categories_course" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "users_course" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "users_course" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "categories_course" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");


// COMMANDS DATABASE
------> IMPORTANTE O NO SE SI LO SEA PERO A MI ME TOCA HACERLO :v <-------

CREATE DATABASE courses_database
// \c courses_database
--------> AHORA SI COPIAR EL CODIGO DE ARRIBA <---------------

// \dt
// \d para describir cada carpeta da la dt

INSERT INTO categories (name) VALUES ('frontend'), ('backend');

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO users (name, email, password, age, roles_id) VALUES ('nicolas', 'nicolas@gmail.com', 'nicolas1234', 22, 1), ('erica', 'erica@gmail.com', 'erica1234', 26, 1), ('alejandra', 'alejandra@academlo.com', 'alejandra1234', 28, 2), ('brenda', 'brenda@academlo.com', 'brenda1234', 30, 2), ('ian', 'ian@academlo.com', 'ian1234', 32, 2), ('erik', 'erik@academlo.
com', 'erik1234', 36, 3), ('georg', 'georg@academlo.com', 'georg1234', 37, 3);

INSERT INTO courses (title, description, level, teacher) VALUES ('fundamentos', 'bases de programacion', 'facil(1)', 3), ('react', 'creacion de aplicaciones', 'intermedio(2)', 4), ('backend', 'bases de datos y mas', 'dificil(3)', 5);

INSERT INTO users_course (users_id, courses_id) VALUES (1, 1), (2, 1), (1, 2), (2, 2), (1, 3), (2, 3);

INSERT INTO course_video (title, url, course_id) VALUES ('html', 'url1', 1), ('css', 'url2', 1), ('javascript', 'url3', 1), ('react', 'url4', 2), ('consumo apis', 'url5', 2), ('ecommers con react', 'url6', 2), ('node js', 'url7', 3), ('base de datos', 'url8', 3);

INSERT INTO categories_course (category_id, course_id) VALUES (1, 1), (2, 1), (3, 2);
// en esta tabla o registro categories_course me sale un error aiuda :v
ERROR:  insert or update on table "categories_course" violates foreign key constraint "categories_course_category_id_fkey"
DETAIL:  Key (category_id)=(3) is not present in table "categories".